In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(x, y)

LogisticRegression(random_state=0, solver='liblinear')

In [ ]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
print("Classes:", model.classes_)
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)


Classes: [0 1]
Intercept: [-1.04608067]
Coefficients: [[0.51491375]]


In [ ]:
print("Predicted probabilities:\n", model.predict_proba(x))
print("Predictions:", model.predict(x))
print("Model score:", model.score(x, y))


Predicted probabilities:
 [[0.74002157 0.25997843]
 [0.62975524 0.37024476]
 [0.5040632  0.4959368 ]
 [0.37785549 0.62214451]
 [0.26628093 0.73371907]
 [0.17821501 0.82178499]
 [0.11472079 0.88527921]
 [0.07186982 0.92813018]
 [0.04422513 0.95577487]
 [0.02690569 0.97309431]]
Predictions: [0 0 0 1 1 1 1 1 1 1]
Model score: 0.9


In [ ]:
print("Confusion matrix:\n", confusion_matrix(y, model.predict(x)))
print("Classification report:\n", classification_report(y, model.predict(x)))


Confusion matrix:
 [[3 1]
 [0 6]]
Classification report:
               precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.86      1.00      0.92         6

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10



In [ ]:
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)


LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [ ]:
print("Classes:", model.classes_)
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)


Classes: [0 1]
Intercept: [-3.51335372]
Coefficients: [[1.12066084]]


In [ ]:
print("Predicted probabilities:\n", model.predict_proba(x))
print("Predictions:", model.predict(x))
print("Model score:", model.score(x, y))


Predicted probabilities:
 [[0.97106534 0.02893466]
 [0.9162684  0.0837316 ]
 [0.7810904  0.2189096 ]
 [0.53777071 0.46222929]
 [0.27502212 0.72497788]
 [0.11007743 0.88992257]
 [0.03876835 0.96123165]
 [0.01298011 0.98701989]
 [0.0042697  0.9957303 ]
 [0.00139621 0.99860379]]
Predictions: [0 0 0 0 1 1 1 1 1 1]
Model score: 1.0


In [ ]:
print("Confusion matrix:\n", confusion_matrix(y, model.predict(x)))

-------------------------------------------------------------------------------------------------------------
print("Classification report:\n", classification_report(y, model.predict(x)))


Confusion matrix:
 [[4 0]
 [0 6]]
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

